version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
# Deploy to GitHub Releases
- provider: GitHub
artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  draft: false
  prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true 
      